package app.nwm.server.notification;

public enum NotificationType {
  WELCOME,
  GENERATION_COMPLETED,
  GENERATION_FAILED,
  SUBSCRIPTION_ACTIVATED,
  SUBSCRIPTION_CANCELED,
  PAYMENT_FAILED,
  PAYMENT_SUCCEEDED,
  TOPUP_PURCHASED
}
